### ISSUE TITLE
Adding the admin API to the router causes a lot extra compilations

### ISSUE THREAD

**Issue by axelson** [ash-project/ash_admin#2]
**Describe the bug**
Adding a snippet like `ash_admin "/admin", apis: [GenTracker.API]` to your phoenix app's router, causes the router to have a lot of compile-time dependencies.

**To Reproduce**
Add a line of `ash_admin "/admin", apis: [GenTracker.API]` to a phoenix app's router and check the output of `mix xref graph --format dot`

**Expected behavior**
Adding ash_admin to not add significant compile-time dependencies to the router.

** Runtime
 - Elixir version: Elixir 1.12.0-rc.0
 - Erlang version: 24.0-rc2
 - OS: Arch Linux
 - Ash version: 1.41.6 
 - any related extension versions ash_admin 0.2.10

**Additional context**
![Screenshot 2021-04-19 08 27 20](https://user-images.githubusercontent.com/9973/115348399-4c074d00-a14e-11eb-96a8-87e900fa4654.png)

**Comment by zachdaniel** [comment]
Yeah, there is a bunch of work done at compile time that should likely just be done by a controller/plug to find the appropriate resources. Anyone who wants to rewrite the router logic to do that is more than welcome :)

**Comment by axelson** [comment]
The main problem is directly the router. Given this definition in the router:

```
    ash_admin "/admin", apis: [GenTracker.API]
```
That causes a compile dependency from the router to GenTracker.API

This means that if we can avoid referencing the MyApp.API (`GenTracker.API`) in this case within the router we would not have the compile-time dependency. I'm working around this right now very hackily with:
```
    # Trick the Elixir compiler
    ash_admin "/admin", apis: ["Elixir.GenTracker.API" |> String.to_atom()]
```
Which is pretty terrible (although it is working well). Another somewhat bad option is to have the user provide the Api's via application config. But a naive approach to that would mean that there could only be a single ash_admin for a project. Of course that could be solved by the user providing a specific key into the application configuration which seems like it will be quite unweildy.

**Comment by zachdaniel** [comment]
So the implementation of the router actually does logically (not just as a detail of mentioning the module name) depend on the api modules at compile time, because it (naively) builds the full list of routes at compile time. To fix it, the router macro should be rewritten to just forward to a `Plug.Router` that has a single match that matches up the routes at runtime. That would also make live reload better as users change their routes.

**Comment by zachdaniel** [comment]
I'm rewriting the router now :)

**Comment by axelson** [comment]
Great!

**Comment by zachdaniel** [comment]
The latest release candidate is out, which actually just does away with routing entirely because, to be honest, it was just a huge PITA to rewrite dynamically. Now it just uses query params, which I figure is fine since its just an admin ui, not something customer facing.

**Comment by zachdaniel** [comment]
It also updates to the latest versions of surface/phoenix and friends, so there may be some issues using it, we'll see. Its working for me in my applications right now though :)
