### ISSUE TITLE
Simple Union type in array of Union types does not save or display correctly

### ISSUE THREAD

**Issue by mkschell** [ash-project/ash_admin#239]
Given a Union field where one of the possible types is a simple type like :string, and when a Resource attribute is an array of these Unions, there are two issues in Ash Admin:

- when that simple type is chosen for the "type" of one of the array values, it passes validation, but errors when saving the resource

- when one of the field's saved array values "type" is one of these simple types like :string, it does not display in the form as type "string"; instead the first available type from the configured union type is selected

To Reproduce

Run Ash Admin with the demo app. This contains a "metadatas" field on the Ticket resource. This field is an _array_ of Demo.Tickets.Ticket.Types.Metadata which is a union of types "foo", "bar" and "string". Both "foo" and "bar" types are defined in modules. "string" is what might be called a "simple type" (not sure if there is a more idiomatic term for this).

- Go to the Update action for the one Ticket resource provided in seeded data. Add an array value to the metadatas field. Confirm that you can choose and save "foo" and "bar" types. Then try adding an array value choosing the "string" type, provide a valid string as the value, and save the resource. This produces an error.
- Update the stored value for the "metadatas" field (assuming postgresql data layer) of the Ticket resource to something like:

`{"{\"type\": \"foo\", \"value\": {\"foo\": 2}}","{\"type\": \"bar\", \"value\": {\"bar\": \"stool\"}}","{\"type\": \"string\", \"value\": \"of bad luck\"}"}`

Then load the Update action for the Ticket resource and see that the type for the third array value, which should be "string" is set to "foo" while the value is displayed correctly.

** Expected behavior **

Expected behavior would be for the user to be able to select the "string" type for one of the "metadatas" field array values, input a valid string value, and save the form. Then for the user to be able to load the form and see that the "string" type is chosen for that array value of the "metadatas" field.

Runtime

    Elixir 1.16.1 (compiled with Erlang/OTP 24)
    MacOS
    Ash version 3.4.46
    ash_phoenix 2.1.10
    ash_postgres 2.4.16

**Comment by netProphET** [comment]
PR incoming
