### ISSUE TITLE
Ash Admin doesn't work with latest Ash?

### ISSUE THREAD

**Issue by delitescere** [ash-project/ash_admin#31]
```
Failed to use "ash" (version 2.1.0) because
  ash_admin (version 0.5.2) requires ~> 1.53 and >= 1.53.1
```

**Comment by zachdaniel** [comment]
`0.6.2` is the latest ash_admin version, and it has a dependency on `~> 2.0` as far as I can tell.  The problem here was that the readme was pointing at an out of date version.

**Comment by zachdaniel** [comment]
Thanks for the report!
