### ISSUE TITLE
Phoenix 1.7 release causing issues w/ ash_admin compilation

### ISSUE THREAD

**Issue by cunningryan** [ash-project/ash_admin#33]
**Describe the bug**
Getting an error when trying to compile Ash Admin to use with Phoenix 1.7. Getting the following error.

```
==> ash_admin
Compiling 29 files (.ex)

== Compilation error in file lib/ash_admin/layout_view.ex ==
** (CompileError) lib/ash_admin/layout_view.ex:3: module Phoenix.View is not loaded and could not be found
    (elixir 1.14.2) expanding macro: Kernel.use/2
    lib/ash_admin/layout_view.ex:3: AshAdmin.LayoutView (module)
    expanding macro: AshAdmin.Web.__using__/1
    lib/ash_admin/layout_view.ex:3: AshAdmin.LayoutView (module)
    (elixir 1.14.2) expanding macro: Kernel.use/2
    lib/ash_admin/layout_view.ex:3: AshAdmin.LayoutView (module)
```

**To Reproduce**
Attempt to compile Ash Admin with Phoenix 1.7

**Expected behavior**
Ash Admin compiles successfully :) 

** Runtime
 - Elixir version: 1.14.2
 - Erlang version: 25.1.1
 - OS: MacOS
 - Ash version: 2.4.12
 - Ash Admin: commit# d255aa01583ae5bb6139dacf0f4abbbbffe096f9
 - Phoenix: 1.7

**Comment by zachdaniel** [comment]
Alright, the phoenix-1.7 branch can now be used until they official release it at which point we can do a release to support it.
