### ISSUE TITLE
error editing fields of type Map

### ISSUE THREAD

**Issue by peillis** [ash-project/ash_admin#4]
I'm not sure if this is an error of ash_admin or I should write the implementation for the Map type.

Protocol.UndefinedError at GET /admin/Layer/DeviceScreen/update/update/g3QAAAABZAACaWRhAw==

protocol Phoenix.HTML.Safe not implemented for %{"min_capture_length" => 3} of type Map. This protocol is implemented for the following type(s): Decimal, Ash.NotLoaded, Ash.CiString, Phoenix.LiveComponent.CID, Phoenix.LiveView.Comprehension, Phoenix.LiveView.Component, Phoenix.LiveView.Rendered, Atom, Time, BitString, Tuple, DateTime, List, NaiveDateTime, Integer, Phoenix.HTML.Form, Date, Float

**Comment by zachdaniel** [comment]
Interesting...is there a stacktrace for the error? We don't (at the moment) support editing elixir maps in the admin dashboard. We can potentially support treating it as json and encoding/decoding, but that is just work that would need to be done. PRs on that front welcome. As for this error, it is likely just a bug that we are even showing an input for that field.

**Comment by peillis** [comment]
The error would be fixed with just this code:
```
defimpl Phoenix.HTML.Safe, for: Map do
  def to_iodata(data), do: data |> Jason.encode! |> Plug.HTML.html_escape
end
```
But I don't know which would be the right place to put this.

**Comment by zachdaniel** [comment]
It's not that simple. You could clone the project down and try it yourself to see what I mean. The *input* provided to the action would always be invalid (a stringified map and/or it would be json encoded which may or may not preserve its properties)

**Comment by zachdaniel** [comment]
@peillis the admin dashboard now supports a json editor for map type data.

**Comment by peillis** [comment]
Great! Thank you
