### ISSUE TITLE
Admin links are not aware of the scope where ash_admin is called

### ISSUE THREAD

**Issue by pierrelegall** [ash-project/ash_admin#45]
**Actual behavior**

`AshAdmin.Router.ash_admin/2` take account of the scope prefix to set the admin route. However, the links in the admin are not aware of. Its just take the path without the scope prefix.

**To Reproduce**

In `router.ex`:

```elixir
    scope "/dev" do
      pipe_through :browser

      ash_admin("/admin")
      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
```

Here, the admin route will be `/dev/admin/*route`, however the links in the admin will goes to `/admin`.

**Expected behavior**

Links of the admin should take account of the scope where `ash_admin` was called, i.e. `/dev/admin` in the example above. 

**Workaround**

My workaround, still in `router.ex`:

```elixir
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end

    scope "/" do
      pipe_through :browser

      # Warning: the Ash admin seems not to be aware of the scope prefix,
      # that's why `ash_admin` is called into a "/" scope
      ash_admin("/dev/admin")
    end
```

**Runtime**
 - Elixir version: 1.14.0
 - Erlang version: 25.2-3
 - OS: Archlinux, GNU/Linux 6.2.2-arch1-1
 - Ash version: 2.6.17
 - Phoenix version: 1.7.1

**Comment by zachdaniel** [comment]
So we should definitely do this differently, as we should likely be able to get this from the path or using route helpers or something, but at the moment, there is a `path` option to `ash_admin`, i.e `ash_admin("/admin", path: "/dev")`. Its not pretty, though since you have to duplicate the scopes its in.

**Comment by zachdaniel** [comment]
I've labeled this as a good first issue. Since there is a reasonable workaround I will probably not tackle this myself in the near future, but PRs welcome!

**Comment by kevinam99** [comment]
Is this still open? Would like to give it a shot

**Comment by zachdaniel** [comment]
Yes, this is still open. Would be great to deprecate that option and replace it with something smarter :D

**Comment by kevinam99** [comment]
Cool. Deprecate which option and what do you have in mind to replace with?

Question. Since something will be deprecated, would it break anything?

**Comment by kevinam99** [comment]
Sounds good! Let's see what I can come up with and we can continue from there?

**Comment by zachdaniel** [comment]
Sounds great! Not sure how easy it will be, could be a one liner

**Comment by kevinam99** [comment]
How? :D

**Comment by kevinam99** [comment]
yep, working on that atm

**Comment by kevinam99** [comment]
Can't seem to get anywhere, but you're right. Need to do this a bit differently

**Comment by zachdaniel** [comment]
Perhaps it has to be done in the plug, maybe if you forward to another plug you can get the path?

**Comment by kevinam99** [comment]
Hi, Zach. I kind of found a way to derive the whole path by using a plug approach, but I'm stuck after that. 

Need to be able to pas the path from the plug to `ash_admin/2` somehow but can't get any ideas yet.

I've opened a draft PR https://github.com/ash-project/ash_admin/pull/49

**Comment by zachdaniel** [comment]
fixed in https://github.com/ash-project/ash_admin/pull/49
