### ISSUE TITLE
Displays resource attributes which are marked as sensitive.

### ISSUE THREAD

**Issue by jimsynz** [ash-project/ash_admin#48]
I can see why there may be a reason you'd want an admin to see these attributes.

At the very minimum it should have a click-to-display widget but should probably have a configuration option (which defaults to off) which lets the user choose between showing it, showing a redacted version or now showing the field at all.

<img width="1203" alt="Screenshot 2023-03-15 at 2 15 46 PM" src="https://user-images.githubusercontent.com/59449/225179782-89289ea2-36f5-49b8-bafd-335be8996a5a.png">
<img width="1203" alt="Screenshot 2023-03-15 at 2 22 07 PM" src="https://user-images.githubusercontent.com/59449/225179810-4c773a95-2c31-4dec-afee-ad3e3fe80f39.png">

**Comment by zachdaniel** [comment]
Agreed. I think we should add some kind of behavior that allows you to define what a given user can/can't do in the admin.
