### ISSUE TITLE
Error on `mix migrate_tenants` command

### ISSUE THREAD

**Issue by BryanJBryce** [ash-project/ash_admin#53]
> To work on ash_admin, you'll want to be able to run the dev app. You'll need to have postgres setup locally, at which point you can do the following:
> 
> mix ash_postgres.create
> mix migrate
> mix migrate_tenants
> Then, you can start the app with: mix dev
> 
> if you make changes to the resources, you can generate migrations with mix generate_migrations

The `mix migrate_tenants` step produces this error:

> ** (Mix) Could not find migrations directory "dev/repo/tenant_migrations"
> for repo Demo.Repo.
> 
> This may be because you are in a new project and the
> migration directory has not been created yet. Creating an
> empty directory at the path above will fix this error.
> 
> If you expected existing migrations to be found, please
> make sure your repository has been properly configured
> and the configured path exists.

**To Reproduce**

Clone down `main` and follow the development instructions. The command: `mix migrate_tenants` will throw an error.

**Expected behavior**

No error when running tenant migrations.

**Runtime**
 - Elixir version: 1.14.3
 - Erlang version 25.2.2
 - OS macOS 13.2.1
 - Ash version 2.4.2

**Comment by zachdaniel** [comment]
this should be fixed in main
