### ISSUE TITLE
In the admin panel, changing an embedded json field in a relationship causes all the fields below that to get deleted

### ISSUE THREAD

**Issue by hanrelan** [ash-project/ash_admin#66]
**Describe the bug**
I have the following action:
```
    update :manage_templates do
      accept []
      argument :templates, {:array, :map}

      change manage_relationship(:templates, type: :direct_control)
    end
```

My Template resource has an attribute like this:
```
    attribute :config, :map, allow_nil?: true
```

If I have several templates, for example, template 1, 2, 3, and template 2 has some keys/values in its `config` map, then editing those values in the `manage_templates` action using the tree editor causes template 3 to be deleted.

**Expected behavior**

It allows me to edit template 2's config without deleting the other templates.

**Runtime**
 - Elixir version: 1.15
 - Erlang version: 25
 - OS: Mac OS
 - Ash version: 2.13.3
 - any related extension versions: ash_admin: 0.9.4

**Comment by zachdaniel** [comment]
I believe this is resolved in recent versions of `ash_admin`. Please let me know if not.
