### ISSUE TITLE
Ash.Unions don't render correctly

### ISSUE THREAD

**Issue by joshprice** [ash-project/ash_admin#71]
**Describe the bug**

An embedded resource with a field defined as an Array of Unions renders like this in Ash Admin:

<img width="727" alt="Screen Shot 2023-08-21 at 6 11 48 pm" src="https://github.com/ash-project/ash_admin/assets/9307/46689789-5c79-4ec8-b81a-a12b31695a5b">

**To Reproduce**

Setup a resource with a field that is an array of Union types.

**Expected behavior**

Another field containing list of non-union embedded types renders fine. 

Presumably it's possible to have this render in some sensible default way despite the fact that each item could be different?

**Runtime**
 - Elixir 1.14.4
 - Erlang 25.3.2
 - OS mac
 - Ash main
 - Ash Admin main

**Comment by zachdaniel** [comment]
Yep! We can do this, just hasn't been implemented yet.

**Comment by netProphET** [comment]
Likely solved via #239 (and PR #240)?
