### ISSUE TITLE
Templates broken in LiveView 0.20

### ISSUE THREAD

**Issue by ArthurClemens** [ash-project/ash_admin#72]
**Describe the bug**

The admin pages render unresolved markup, while the developer console spews errors "only HTML element tags are allowed at the root of components.

<img width="1920" alt="admin-template-errors" src="https://github.com/ash-project/ash_admin/assets/350303/b36d37e7-d554-42a3-91d6-061e6892af23">

**To Reproduce**

1. Follow the steps in [Get Started with Ash and Phoenix](https://www.ash-hq.org/docs/guides/ash_phoenix/latest/tutorials/getting-started-with-ash-and-phoenix).
2. Follow the steps in the ash_admin README to add Admin pages.
3. Start server and visit any admin page.

The problem is clearly introduced with`phoenix_live_view` version 0.20, as it disappears with a downgrade using deps config `{:phoenix_live_view, "0.19.5"}`.

**Comment by zachdaniel** [comment]
I won't have time to look at this in the near future, anyone who does it would be greatly appreciated. It essentially boils down to wrapping some components in `<div` (or something along those lines)

**Comment by ArthurClemens** [comment]
I've tried some things, but it seems it is not as simple as adding some `div` wrappers.

**Comment by juhalehtonen** [comment]
I've tried to have a quick look at what exactly makes ash_admin break with the annotations enabled, but haven't figured it out yet.

It is probably obvious from the error messages and the Phoenix LiveView [changelog](https://github.com/phoenixframework/phoenix_live_view/blob/main/CHANGELOG.md), but this seems to related to the new "heex debug annotations".

I can confirm this problem occurs with `{:ash_admin, "~> 0.9.5"}` and `{:phoenix_live_view, "~> 0.20.1"}`.

I can also confirm that the problem goes away when I configure my project to not use the new debug annotations (`config :phoenix_live_view, :debug_heex_annotations, false` and I then recompile `ash_admin` with `mix deps.compile --force ash_admin`. With the setting disabled, the HTML comments are no longer added and the LiveViewJS error doesn't occur.

**Comment by jimsynz** [comment]
Thanks for finding the workaround @juhalehtonen. At least that unblocks people while we're looking at a fix.

**Comment by col** [comment]
For some reason the workaround didn't work for me. I disable `debug_heex_annotations` in my app config and force compiled `ash_admin`. Not sure what I'm missing. I've had to downgrade `phoenix_live_view ` to `0.19.5` for now.

**Comment by zachdaniel** [comment]
This is interesting. Running `mix dev` in `ash_admin` doesn't have this same issue after updating all of the dependencies. Does updating all of your dependencies solve this issue?

**Comment by jimsynz** [comment]
@sevenseacat

**Comment by sevenseacat** [comment]
okay I can definitely see this is an issue. Looking into it!

@zachdaniel - it only happens when adding the config to enable heex annotations, eg. `config :phoenix_live_view, :debug_heex_annotations, true` in `config.exs`
