### ISSUE TITLE
PageLive crashes in the dev app when attempting to view/edit a Ticket resource

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash_admin#79]
It seems to be related to changes around `to_one_relationships` made recently?

This error gets generated when the liveview crashes - 

```
 ** (CaseClauseError) no case clause matching: #Demo.Tickets.Ticket<reporter_name: 
#Ash.NotLoaded<:aggregate>, destination_links: #Ash.NotLoaded<:relationship>, source_links: 
#Ash.NotLoaded<:relationship>, comments: #Ash.NotLoaded<:relationship>, organization: 
#Demo.Tickets.Organization<tickets: #Ash.NotLoaded<:relationship>, __meta__: 
#Ecto.Schema.Metadata<:loaded, "organizations">, id: "1b2b526e-d801-4b1f-8a28-bf58f8648ebd", name: 
"Ash Project", aggregates: %{}, calculations: %{}, ...>, ...>
        (ash_admin 0.9.5) lib/ash_admin/pages/page_live.ex:256: AshAdmin.PageLive.handle_params/3
        ....
```

Which is here - 

https://github.com/ash-project/ash_admin/blob/main/lib/ash_admin/pages/page_live.ex#L256-L264

`record` is previously set to a resource struct, so will never match anything in that case statement.

I feel like the warning could possibly move up into the `socket.assigns.api.load` case clause, and the rest deleted?

**Comment by zachdaniel** [comment]
Yep, you are 100% correct.
