### ISSUE TITLE
Actions are accessible despite not being enabled?

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash_admin#89]
**Describe the bug**

I thought if I set `read_actions` in a resource, that I would not be able to access any other read action. The dropdown UI correctly only lists the actions that are listed in `read_actions`, but editing the URL allows any action to be accessed?

**To Reproduce**

eg. in a resource: 

```elixir
  actions do
    defaults [:read, :create, :update]

    read :find_by_appointment_id do
      argument :appointment_id, :uuid, allow_nil?: false

      prepare build(sort: [event_ts: :desc], load: [:occurred_at])
      filter expr(appointment_id == ^arg(:appointment_id))
    end
  end

  admin do
    read_actions [:read]
  end
```

Accessing http://localhost:4000/admin?api=MyApi&resource=MyResource&table=&action_type=read&action=find_by_appointment_id still works, renders the form to enter an appointment ID, and then will run the query.

**Expected behavior**

An error when accessing a disabled action.

**Runtime**
 - Ash version main at 7b5a3267beb385b22c174c979649cae4ff57635d
 - Ash Admin main at 92f9997fa390602103b49554e5b8fe5e9ebb7590

**Comment by zachdaniel** [comment]
🤔 yeah thats not ideal at all

**Comment by zachdaniel** [comment]
Fixed in latest release.
