### ISSUE TITLE
Hide resources on demand.

### ISSUE THREAD

**Issue by jechol** [ash-project/ash_admin#90]
**Is your feature request related to a problem? Please describe.**
I'm using ash_paper_trail for my resources, and since all resources in the API are included, Version resources make the list too messy.

**Describe the solution you'd like**
In the resource, I can set it to be hidden.

**Express the feature either with a change to resource syntax, or with a change to the resource interface**

```elixir
use Ash.Resource, extensions: [AshAdmin.Resource]

admin do
  show? false
end
```

**Comment by zachdaniel** [comment]
You can do this with the mixing: https://hexdocs.pm/ash_paper_trail/0.1.0/get-started-with-paper-trail.html#enriching-the-versions-resource

**Comment by jechol** [comment]
@zachdaniel 

I don't understand, could you provide more information? 

As far as I know, there's no show? option in `admin` section of AshAdmin.Resource.

**Comment by zachdaniel** [comment]
Oh, wow. I didn't realize we only had it for apis :(
